project:
  type: website
  output-dir: docs

website:
  title: "Lim Jing Yu"
  favicon: favicon.png
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - href: project.qmd
        text: Intern Project in LTA
      - href: travel.qmd
        text: Travel Experience to Thailand
      - href: reflection.qmd
        text: Reflection

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left


